project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://in-search-of-lost-data.com # you must change this appropriately for RSS feeds to work properly
  title: "In Search Of Lost Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rschaeper
      #- icon: twitter
      #  href: https://twitter.com
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css

execute: 
  message: false
  warning: false



